// Bundle the CLI into the single file dist/explain.mjs.
// The output references neither node_modules nor src/, so it runs on its own wherever Node is installed.
import { build, type Plugin } from 'esbuild';
import { copyFileSync, existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8');

// Replace src/assets.ts with inline strings so nothing is read from disk at run time.
const inlineAssets: Plugin = {
  name: 'inline-assets',
  setup(b) {
    b.onLoad({ filter: /src[\\/]assets\.ts$/ }, () => ({
      loader: 'js',
      contents: [
        `export const VERSION = ${JSON.stringify(JSON.parse(read('../package.json')).version)};`,
        `export const BASE_CSS = ${JSON.stringify(read('../src/themes/base.css'))};`,
        `export const RUNTIME_JS = ${JSON.stringify(read('../src/runtime/page.js'))};`,
        `export const VIDEO_CSS = ${JSON.stringify(read('../src/themes/video.css'))};`,
        `export const VIDEO_JS = ${JSON.stringify(read('../src/runtime/video.js'))};`,
      ].join('\n'),
    }));
  },
};

const outfile = fileURLToPath(new URL('../dist/explain.mjs', import.meta.url));

await build({
  entryPoints: [fileURLToPath(new URL('../bin/explain.ts', import.meta.url))],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  minify: true,
  charset: 'utf8',
  legalComments: 'eof',
  banner: { js: '// explain CLI — generated by scripts/build.ts. Do not edit.' },
  plugins: [inlineAssets],
  logLevel: 'info',
});

// The explain-for-understanding skill runs its own copy of the bundle. Keep it in sync when the skill is installed.
const skillScripts = join(homedir(), '.claude/skills/explain-for-understanding/scripts');
if (existsSync(skillScripts)) {
  copyFileSync(outfile, join(skillScripts, 'explain.mjs'));
  console.log(`  copied to ${join(skillScripts, 'explain.mjs')}`);
}
