// Bundle the CLI into the single file skills/explain/scripts/explain.mjs, which the plugin ships and the skill runs.
// The output references neither node_modules nor src/, so it runs on its own wherever Node is installed.
// Pass a path as the first argument to write the bundle somewhere else (tests use this).
import { build, type Plugin } from 'esbuild';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8');

// Replace src/assets.ts with inline strings so nothing is read from disk at run time.
const inlineAssets: Plugin = {
  name: 'inline-assets',
  setup(b) {
    b.onLoad({ filter: /src[\\/]assets\.ts$/ }, () => ({
      loader: 'js',
      contents: [
        `export const VERSION = ${JSON.stringify(JSON.parse(read('../package.json')).version)};`,
        `export const BASE_CSS = ${JSON.stringify(read('../src/themes/base.css'))};`,
        `export const RUNTIME_JS = ${JSON.stringify(read('../src/runtime/page.js'))};`,
        `export const VIDEO_CSS = ${JSON.stringify(read('../src/themes/video.css'))};`,
        `export const VIDEO_JS = ${JSON.stringify(read('../src/runtime/video.js'))};`,
      ].join('\n'),
    }));
  },
};

await build({
  entryPoints: [fileURLToPath(new URL('../bin/explain.ts', import.meta.url))],
  outfile: process.argv[2] ? resolve(process.argv[2]) : fileURLToPath(new URL('../skills/explain/scripts/explain.mjs', import.meta.url)),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  minify: true,
  charset: 'utf8',
  legalComments: 'eof',
  banner: { js: '// explain CLI — generated by scripts/build.ts. Do not edit.' },
  plugins: [inlineAssets],
  logLevel: 'info',
});
