// CLI を 1 ファイル dist/explain.mjs にまとめる。
// 生成物は node_modules も src/ も参照しないので、Node があればこのファイル単体で動く。
import { build, type Plugin } from 'esbuild';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8');

// src/assets.ts をインライン文字列に差し替え、実行時にディスク上のファイルを読まないようにする。
const inlineAssets: Plugin = {
  name: 'inline-assets',
  setup(b) {
    b.onLoad({ filter: /src[\\/]assets\.ts$/ }, () => ({
      loader: 'js',
      contents: [
        `export const VERSION = ${JSON.stringify(JSON.parse(read('../package.json')).version)};`,
        `export const BASE_CSS = ${JSON.stringify(read('../src/themes/base.css'))};`,
        `export const RUNTIME_JS = ${JSON.stringify(read('../src/runtime/page.js'))};`,
        `export const VIDEO_CSS = ${JSON.stringify(read('../src/themes/video.css'))};`,
        `export const VIDEO_JS = ${JSON.stringify(read('../src/runtime/video.js'))};`,
      ].join('\n'),
    }));
  },
};

await build({
  entryPoints: [fileURLToPath(new URL('../bin/explain.ts', import.meta.url))],
  outfile: fileURLToPath(new URL('../dist/explain.mjs', import.meta.url)),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  minify: true,
  charset: 'utf8',
  legalComments: 'eof',
  banner: { js: '// explain CLI — generated by scripts/build.ts. Do not edit.' },
  plugins: [inlineAssets],
  logLevel: 'info',
});
